package com.example.jh.rxhapp.utils;

/**
 * Created by jh on 2017/5/25.
 */

public class HtmlBody {
    public static final String Html =  "<P>&nbsp;</P><br /><P>&nbsp;</P><br /><P><span class=\"lia-inline-image-display-wrapper lia-image-align-inline\" style=\"width: 555px;\"><img src=\"https://lnv.i.lithium.com/t5/image/serverpage/image-id/92762i192B212B6CC4F2EE/image-size/large?v=1.0&amp;px=999\" alt=\"Lenovo Code and Play.PNG\" title=\"Lenovo Code and Play.PNG\" /></span></P><br /><P>&nbsp;<FONT size=\"1 2 3 4 5 6 7\"><SPAN>* Only available to legal residents of the United States, United Kingdom, and Germany. Please </SPAN><A class=\"aqua\" href=\"https://lenovogamestate.com/rules/\" target=\"_blank\" rel=\"nofollow noopener noreferrer\">see full rules</A><SPAN> for details.</SPAN></FONT></P><br /><P>&nbsp;</P><br /><H2 class=\"aqua\" id=\"toc-hId-502702703\">WHAT IS CODE &amp; PLAY?</H2><br /><P class=\"copy grey-dark bigger topmarg\"><span class=\"lia-inline-image-display-wrapper lia-image-align-inline\" style=\"width: 159px;\"><img src=\"https://lnv.i.lithium.com/t5/image/serverpage/image-id/92763i5F33835347906EAE/image-size/medium?v=1.0&amp;px=400\" width=\"159\" height=\"368\" alt=\"Character1_about.png\" title=\"Character1_about.png\" /></span>Code &amp; Play is a new program developed by Lenovo to introduce kids and teens to coding in a way that closely resembles a traditional computer game. Code &amp; Play was designed to support a STEM-based education, and equips young people with skills that are beneficial to their future.</P><br /><P class=\"copy grey-dark bigger topmarg\">&nbsp;</P><br /><P class=\"copy grey-dark bigger topmarg\">&nbsp;</P><br /><P class=\"copy grey-dark bigger topmarg\"><SPAN><span class=\"lia-inline-image-display-wrapper lia-image-align-inline\" style=\"width: 159px;\"><img src=\"https://lnv.i.lithium.com/t5/image/serverpage/image-id/92764iE706002D06D5D4D2/image-size/small?v=1.0&amp;px=200\" width=\"159\" height=\"126\" alt=\"chest.png\" title=\"chest.png\" /></span>After you sign up and get started with Code &amp; Play you’ll be entered to win a $2,500 scholarship to a coding school or camp. Each level you complete counts towards an additional entry, so </SPAN><SPAN class=\"emphatic\">THE MORE YOU CODE, THE MORE CHANCES YOU HAVE TO WIN!</SPAN></P><br /><P class=\"copy grey-dark bigger topmarg\">&nbsp;</P><br /><P class=\"copy grey-dark bigger topmarg\"><SPAN class=\"emphatic\"><span class=\"lia-inline-image-display-wrapper lia-image-align-inline\" style=\"width: 999px;\"><img src=\"https://lnv.i.lithium.com/t5/image/serverpage/image-id/92765iC7D213603E986CC8/image-size/large?v=1.0&amp;px=999\" alt=\"banner.PNG\" title=\"banner.PNG\" /></span></SPAN></P><br /><P class=\"copy grey-dark bigger topmarg\">&nbsp;</P><br /><P class=\"copy grey-dark bigger topmarg\"><A href=\"https://lenovogamestate.com/codeplay/\" target=\"_blank\" rel=\"nofollow noopener noreferrer\">REGISTER HERE</A></P>";
}
